meta:
  description: farmr
  vendor: farmr
  maintainer: farmr
files:
  "/usr/bin/farmr":
    file: farmr_package
    mode: "0755"
    user: "root"
  "/etc/systemd/user/farmr.service":
    file: .github/workflows/farmr.service
    mode: "0755"
    user: "root"
  "/etc/farmr/config.json":
    file: config.json
    mode: "0644"
    user: "root"
    keep: true
units:
  #- .github/workflows/farmr.service
scripts:
  "post-install": .github/workflows/post-inst
user: foo