meta:
  description: farmr
  vendor: farmr
  maintainer: farmr
files:
  "/usr/bin/farmr":
    file: farmr
    mode: "0755"
    user: "root"
  "/etc/farmr/config":
    file: config.json.default
    mode: "0644"
    user: "root"
    keep: true
units:
  #- .github/workflows/farmr.service
scripts:
  "post-install": .github/workflows/post-inst
user: foo