name: joaquimbot
version: 1.1.0
description: 
environment: 
  sdk: '>=2.10.0 < 3.0.0'
dependencies:
  path: ^1.8.0
  uuid: ^3.0.4
  yaml: ^3.1.0
  http: ^0.12.2
  filesize: ^1.0.4
  dart_console: ^1.0.0
  qr: ^2.0.0
  universal_disk_space: ^0.1.13
  stats: ^2.0.0
  intl: ^0.17.0
