name: chiabot
version: 1.2.5
description: 
environment: 
  sdk: '>=2.10.0 < 3.0.0'
dependencies:
  path: ^1.8.0
  uuid: ^3.0.4
  yaml: ^3.1.0
  http: ^0.12.2
  filesize: ^1.0.4
  dart_console: ^1.0.0
  qr: ^2.0.0
  universal_disk_space: ^0.1.15
  stats: ^2.0.0
  intl: ^0.17.0
  logging: ^1.0.1
  dotenv: ^2.0.0
  mysql1: ^0.19.2
