name: farmr_client
version: 1.4.0
publish_to: none
description: 
environment: 
  sdk: '>=2.12.0 < 3.0.0'
dependencies:
  path: ^1.8.0
  uuid: ^3.0.4
  yaml: ^3.1.0
  http: ^0.13.3
#  dart_console: ^1.0.0  REMOVING thiS IT IS INCOMPATIBLE WITH JS
  universal_disk_space: ^0.1.20
  stats: ^2.0.0
  intl: ^0.17.0
  logging: ^1.0.1
  dotenv: ^3.0.0
  mysql1: ^0.19.2
  universal_io: ^2.0.4
  environment_config: ^3.0.0
  system_info: 
    git:
      url: https://github.com/joaquimguimaraes/system_info.git
      ref: e81ac3a5777eb486e6853b64a7c68ee22eba7389
  collection: ^1.15.0
