# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: chiabot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  arm64:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: wget
        uses: wei/wget@v1
        with:
          args: -O dart.zip https://storage.googleapis.com/dart-archive/channels/stable/release/2.12.4/sdk/dartsdk-linux-arm64-release.zip
      
      - name: Decompress
        uses: TonyBogdanov/zip@1.0
        with:
          args: unzip -qq ./dart.zip -d .
          
      - uses: uraimo/run-on-arch-action@v2.0.9
        name: Building Linux Arm release
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu20.04
          if: matrix.arch == 'arm64'
          run: |
             ls
#gets dependencies
             ./dart-sdk/bin/dart pub get
#generates environment config
             ./dart-sdk/bin/dart run environment_config:generate
             mv .github/workflows/config.test .github/workflows/config.yaml
             mv .github/workflows/farmer.sh ./farmer.sh
             mv .github/workflows/harvester.sh ./harvester.sh
             mv .github/workflows/hpool.sh ./hpool.sh
             chmod +x ./farmer.sh
             chmod +x ./harvester.sh
             chmod +x ./hpool.sh
#compiles chiabot
             ./dart-sdk/bin/dart compile exe chiabot.dart
             chmod +x chiabot.exe
             mv chiabot.exe chiabot
             mv config.json.default config.json
             tar -czvf ./chiabot-linux-arm64.tar.gz ./chiabot ./config.json ./farmer.sh ./harvester.sh ./hpool.sh
      
      - name: Build DEB file for arm64
        if: matrix.arch == 'arm64'
        uses: kentik/pkg@v1.0.0-rc7
        with:
          distro: ubuntu20.04
          # Package name
          name: chiabot
          # Package version
          version: 1.3.4
          arch: arm64  # optional, default is x86_64
          format: deb
          package: .github/armpackage.yaml
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: Release ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: true
          files: |
            ./chiabot_1.3.4-1_arm64.deb
            ./chiabot-linux-arm64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # You don't need to add this in secrets it's by default.
  amd64:
    # A strategy is used to define various build environments this job will run.
    #
    # To say it simple, this will create 3 separate independent jobs which will
    # run on ubuntu, mac & windows.
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        architecture: [x64]
        
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      
      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@v1
        with:
          architecture: ${{ matrix.architecture }}
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Generate EnvironmentConfig
        run: dart run environment_config:generate

      - name: Analyze project source
        run: dart analyze

      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2

      - name: Building Linux release
        if: matrix.os == 'ubuntu-latest' && matrix.architecture == 'x64'
        run: |
             mv .github/workflows/config.test .github/workflows/config.yaml
             mv .github/workflows/farmer.sh ./farmer.sh
             mv .github/workflows/harvester.sh ./harvester.sh
             chmod +x ./farmer.sh
             chmod +x ./harvester.sh
             mv .github/workflows/hpool.sh ./hpool.sh
             chmod +x ./hpool.sh
             dart compile exe chiabot.dart
             chmod +x chiabot.exe
             ./chiabot.exe harvester onetime
             mv chiabot.exe chiabot
             tar -czvf ./chiabot-linux-amd64-${{ env.version }}.tar.gz ./chiabot ./config.json ./farmer.sh ./harvester.sh ./hpool.sh
        
      - name: Build DEB file for x64
        if: matrix.os == 'ubuntu-latest' && matrix.architecture == 'x64'
        uses: kentik/pkg@v1.0.0-rc7
        with:
          # Package name
          name: chiabot
          # Package version
          version: ${{ env.version }}
          arch: amd64  # optional, default is x86_64
          format: deb
          package: .github/x64package.yaml
        
      - name: Building macOS release
        if: matrix.os == 'macos-latest' && matrix.architecture == 'x64'
        run: |
             mv .github/workflows/config.test .github/workflows/config.yaml
             mv .github/workflows/farmer.sh ./farmer.sh
             mv .github/workflows/harvester.sh ./harvester.sh
             chmod +x ./farmer.sh
             chmod +x ./harvester.sh
             mv .github/workflows/hpool.sh ./hpool.sh
             chmod +x ./hpool.sh
             dart compile exe chiabot.dart
             chmod +x chiabot.exe
             ./chiabot.exe harvester onetime
             mv chiabot.exe chiabot
             tar -czvf ./chiabot-macOS-amd64-${{ env.version }}.tar.gz ./chiabot ./config.json ./farmer.sh ./harvester.sh ./hpool.sh
             
      - name: Building Windows release
        if: matrix.os == 'windows-latest' && matrix.architecture == 'x64'
        run: |
             mv .github/workflows/config.test .github/workflows/config.yaml
             dart compile exe chiabot.dart
             dart compile exe chiabot_harvester.dart
             dart compile exe chiabot_hpool.dart
             ./chiabot.exe harvester onetime
             move ./chiabot.exe ./farmer.exe
             move ./chiabot_hpool.exe ./hpool.exe
             move ./chiabot_harvester.exe ./harvester.exe
             
      - name: Build
        shell: bash
        if: matrix.os == 'windows-latest' && matrix.architecture == 'x64'
        run: |
          # Pack files WINDOWS
          7z a -tzip "chiabot-windows-amd64-${{ env.version }}.zip" "./*.exe" "./config.json"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.version }}
          release_name: ${{ env.version }}
          draft: true
          files: |
            ./chiabot-windows-amd64-${{ env.version }}.zip
            ./chiabot-linux-amd64-${{ env.version }}.tar.gz
            ./chiabot-macOS-amd64-${{ env.version }}.tar.gz
            ./chiabot_${{ env.version }}-1_amd64.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # You don't need to add this in secrets it's by default.
          
          
